export const fallbackVenues = [
  {
    id: "seed-nightmoves",
    canonicalVenueKey: "nightmoves-new-york",
    googlePlaceId: null,
    name: "Nightmoves",
    address: "Williamsburg, Brooklyn, NY",
    neighborhood: "Williamsburg",
    city: "New York",
    types: ["bar", "night_club"],
    location: { lat: 40.7147, lng: -73.9614 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-le-bain",
    canonicalVenueKey: "le-bain-new-york",
    googlePlaceId: null,
    name: "Le Bain",
    address: "Meatpacking District, New York, NY",
    neighborhood: "Meatpacking",
    city: "New York",
    types: ["bar", "night_club"],
    location: { lat: 40.7409, lng: -74.0088 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-public-records",
    canonicalVenueKey: "public-records-new-york",
    googlePlaceId: null,
    name: "Public Records",
    address: "Gowanus, Brooklyn, NY",
    neighborhood: "Gowanus",
    city: "New York",
    types: ["bar", "night_club", "live_music_venue"],
    location: { lat: 40.6781, lng: -73.9863 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-sweet-liberty",
    canonicalVenueKey: "sweet-liberty-miami",
    googlePlaceId: null,
    name: "Sweet Liberty",
    address: "Miami Beach, FL",
    neighborhood: "Miami Beach",
    city: "Miami",
    types: ["bar"],
    location: { lat: 25.7907, lng: -80.1300 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-club-space",
    canonicalVenueKey: "club-space-miami",
    googlePlaceId: null,
    name: "Club Space",
    address: "Downtown Miami, FL",
    neighborhood: "Downtown",
    city: "Miami",
    types: ["night_club"],
    location: { lat: 25.7851, lng: -80.1936 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-death-co-la",
    canonicalVenueKey: "death-and-co-los-angeles",
    googlePlaceId: null,
    name: "Death & Co",
    address: "Arts District, Los Angeles, CA",
    neighborhood: "Arts District",
    city: "Los Angeles",
    types: ["bar"],
    location: { lat: 34.0441, lng: -118.2327 },
    source: "seed",
    photoUrl: null
  }
];
