export const fallbackVenues = [
  {
    id: "seed-nightmoves",
    canonicalVenueKey: "nightmoves-new-york",
    googlePlaceId: null,
    name: "Nightmoves",
    address: "Williamsburg, Brooklyn, NY",
    neighborhood: "Williamsburg",
    city: "New York",
    types: ["bar", "night_club"],
    location: { lat: 40.7147, lng: -73.9614 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-le-bain",
    canonicalVenueKey: "le-bain-new-york",
    googlePlaceId: null,
    name: "Le Bain",
    address: "Meatpacking District, New York, NY",
    neighborhood: "Meatpacking",
    city: "New York",
    types: ["bar", "night_club"],
    location: { lat: 40.7409, lng: -74.0088 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-public-records",
    canonicalVenueKey: "public-records-new-york",
    googlePlaceId: null,
    name: "Public Records",
    address: "Gowanus, Brooklyn, NY",
    neighborhood: "Gowanus",
    city: "New York",
    types: ["bar", "night_club", "live_music_venue"],
    location: { lat: 40.6781, lng: -73.9863 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-smugglers-cove",
    canonicalVenueKey: "smugglers-cove-san-francisco",
    googlePlaceId: null,
    name: "Smuggler's Cove",
    address: "Hayes Valley, San Francisco, CA",
    neighborhood: "Hayes Valley",
    city: "San Francisco",
    types: ["bar"],
    location: { lat: 37.7794, lng: -122.4232 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-monarch",
    canonicalVenueKey: "monarch-san-francisco",
    googlePlaceId: null,
    name: "Monarch",
    address: "SoMa, San Francisco, CA",
    neighborhood: "SoMa",
    city: "San Francisco",
    types: ["bar", "night_club"],
    location: { lat: 37.7809, lng: -122.4085 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-temple-nightclub",
    canonicalVenueKey: "temple-nightclub-san-francisco",
    googlePlaceId: null,
    name: "Temple Nightclub",
    address: "SoMa, San Francisco, CA",
    neighborhood: "SoMa",
    city: "San Francisco",
    types: ["night_club"],
    location: { lat: 37.7878, lng: -122.3972 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-death-co-la",
    canonicalVenueKey: "death-and-co-los-angeles",
    googlePlaceId: null,
    name: "Death & Co",
    address: "Arts District, Los Angeles, CA",
    neighborhood: "Arts District",
    city: "Los Angeles",
    types: ["bar"],
    location: { lat: 34.0441, lng: -118.2327 },
    source: "seed",
    photoUrl: null
  }
];
