export const fallbackVenues = [
  {
    id: "seed-nightmoves",
    canonicalVenueKey: "nightmoves-new-york",
    googlePlaceId: null,
    name: "Nightmoves",
    address: "Williamsburg, Brooklyn, NY",
    neighborhood: "Williamsburg",
    city: "New York",
    types: ["bar", "night_club"],
    location: { lat: 40.7147, lng: -73.9614 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-le-bain",
    canonicalVenueKey: "le-bain-new-york",
    googlePlaceId: null,
    name: "Le Bain",
    address: "Meatpacking District, New York, NY",
    neighborhood: "Meatpacking",
    city: "New York",
    types: ["bar", "night_club"],
    location: { lat: 40.7409, lng: -74.0088 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-public-records",
    canonicalVenueKey: "public-records-new-york",
    googlePlaceId: null,
    name: "Public Records",
    address: "Gowanus, Brooklyn, NY",
    neighborhood: "Gowanus",
    city: "New York",
    types: ["bar", "night_club", "live_music_venue"],
    location: { lat: 40.6781, lng: -73.9863 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-dead-rabbit",
    canonicalVenueKey: "the-dead-rabbit-new-york",
    googlePlaceId: null,
    name: "The Dead Rabbit",
    address: "Financial District, New York, NY",
    neighborhood: "FiDi",
    city: "New York",
    types: ["bar"],
    location: { lat: 40.7033, lng: -74.0112 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-attaboy",
    canonicalVenueKey: "attaboy-new-york",
    googlePlaceId: null,
    name: "Attaboy",
    address: "Lower East Side, New York, NY",
    neighborhood: "Lower East Side",
    city: "New York",
    types: ["bar"],
    location: { lat: 40.7189, lng: -73.9901 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-house-of-yes",
    canonicalVenueKey: "house-of-yes-new-york",
    googlePlaceId: null,
    name: "House of Yes",
    address: "Bushwick, Brooklyn, NY",
    neighborhood: "Bushwick",
    city: "New York",
    types: ["night_club", "live_music_venue"],
    location: { lat: 40.7068, lng: -73.9238 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-elsewhere",
    canonicalVenueKey: "elsewhere-new-york",
    googlePlaceId: null,
    name: "Elsewhere",
    address: "Bushwick, Brooklyn, NY",
    neighborhood: "Bushwick",
    city: "New York",
    types: ["night_club", "live_music_venue"],
    location: { lat: 40.7095, lng: -73.9232 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-swan-room",
    canonicalVenueKey: "swan-room-new-york",
    googlePlaceId: null,
    name: "Swan Room",
    address: "Lower East Side, New York, NY",
    neighborhood: "Lower East Side",
    city: "New York",
    types: ["bar", "night_club"],
    location: { lat: 40.7216, lng: -73.9933 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-jupiter-disco",
    canonicalVenueKey: "jupiter-disco-new-york",
    googlePlaceId: null,
    name: "Jupiter Disco",
    address: "Bushwick, Brooklyn, NY",
    neighborhood: "Bushwick",
    city: "New York",
    types: ["bar", "night_club"],
    location: { lat: 40.7054, lng: -73.9337 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-good-room",
    canonicalVenueKey: "good-room-new-york",
    googlePlaceId: null,
    name: "Good Room",
    address: "Greenpoint, Brooklyn, NY",
    neighborhood: "Greenpoint",
    city: "New York",
    types: ["night_club"],
    location: { lat: 40.7269, lng: -73.9515 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-bemelmans-bar",
    canonicalVenueKey: "bemelmans-bar-new-york",
    googlePlaceId: null,
    name: "Bemelmans Bar",
    address: "Upper East Side, New York, NY",
    neighborhood: "Upper East Side",
    city: "New York",
    types: ["bar"],
    location: { lat: 40.7745, lng: -73.9631 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-sel-rose",
    canonicalVenueKey: "sel-rose-new-york",
    googlePlaceId: null,
    name: "Sel Rrose",
    address: "Bowery, New York, NY",
    neighborhood: "Bowery",
    city: "New York",
    types: ["bar"],
    location: { lat: 40.7212, lng: -73.9940 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-mr-fongs",
    canonicalVenueKey: "mr-fongs-new-york",
    googlePlaceId: null,
    name: "Mr. Fong's",
    address: "Chinatown, New York, NY",
    neighborhood: "Chinatown",
    city: "New York",
    types: ["bar"],
    location: { lat: 40.7149, lng: -73.9975 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-smugglers-cove",
    canonicalVenueKey: "smugglers-cove-san-francisco",
    googlePlaceId: null,
    name: "Smuggler's Cove",
    address: "Hayes Valley, San Francisco, CA",
    neighborhood: "Hayes Valley",
    city: "San Francisco",
    types: ["bar"],
    location: { lat: 37.7794, lng: -122.4232 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-monarch",
    canonicalVenueKey: "monarch-san-francisco",
    googlePlaceId: null,
    name: "Monarch",
    address: "SoMa, San Francisco, CA",
    neighborhood: "SoMa",
    city: "San Francisco",
    types: ["bar", "night_club"],
    location: { lat: 37.7809, lng: -122.4085 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-temple-nightclub",
    canonicalVenueKey: "temple-nightclub-san-francisco",
    googlePlaceId: null,
    name: "Temple Nightclub",
    address: "SoMa, San Francisco, CA",
    neighborhood: "SoMa",
    city: "San Francisco",
    types: ["night_club"],
    location: { lat: 37.7878, lng: -122.3972 },
    source: "seed",
    photoUrl: null
  },
  {
    id: "seed-death-co-la",
    canonicalVenueKey: "death-and-co-los-angeles",
    googlePlaceId: null,
    name: "Death & Co",
    address: "Arts District, Los Angeles, CA",
    neighborhood: "Arts District",
    city: "Los Angeles",
    types: ["bar"],
    location: { lat: 34.0441, lng: -118.2327 },
    source: "seed",
    photoUrl: null
  }
];
